apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

          volumeMounts:
            # Grafana data
            - name: grafana-data
              mountPath: /var/lib/grafana

            # Dashboards (JSON + gnet provisioning)
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards

            # Dashboard providers
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards

            # Datasources
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources

      volumes:
        - name: grafana-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}

        - name: grafana-dashboard
          configMap:
            name: {{ .Release.Name }}-dashboard

        - name: grafana-dashboards-config
          configMap:
            name: {{ .Release.Name }}-dashboards-config

        - name: grafana-datasource
          configMap:
            name: {{ .Release.Name }}-datasource
