apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-agent
  namespace: {{ .Values.nameSpace }}
  labels:
    app: portainer-agent
spec:
  replicas: {{ .Values.replicaCountAgent }}
  selector:
    matchLabels:
      app: portainer-agent
  template:
    metadata:
      labels:
        app: portainer-agent
    spec:
      serviceAccountName: portainer-sa
      containers:
        - name: portainer-agent
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag }}"
          imagePullPolicy: {{ .Values.image.agent.pullPolicy }}
          env:
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 9001
