apiVersion: v1
kind: Service
metadata:
  name: s-portainer-agent-headless
  namespace: {{ .Values.nameSpace }}
  labels:
    app: portainer-agent
spec:
  clusterIP: None
  selector:
    app: portainer-agent
  ports:
    - name: http
      port: 9001
      targetPort: 9001
