apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.service.portainer.type }}
  ports:
    - port: {{ .Values.service.portainer.port }}
      targetPort: 9000
      protocol: TCP
  selector:
    app: portainer
