prometheus:
  image: prom/prometheus:v2.46.0
  service:
    type: NodePort
    port: 9090
    nodePort: 30900
  scrapeInterval: 15s
  evaluationInterval: 15s

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: prom.devops-tools-dev.ps.speechpro.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
