apiVersion: v1
kind: Service
metadata:
  name: portainer
spec:
  type: {{ .Values.service.type }}
  selector:
    app: portainer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      nodePort: {{ .Values.service.nodePort }}
