image:
  repository: portainer/portainer-ce
  tag: "2.19.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000
  nodePort: 30990

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""  # default

resources: {}
