apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: {{ .Values.nodeExporter.image }}
          ports:
            - containerPort: 9100
              hostPort: {{ .Values.nodeExporter.hostPort }}
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
